name: bluesky_post_joke

on:
  schedule:
    - cron:  '0 0,8,16 * * *'
  workflow_dispatch:

jobs:
  bluesky_post_joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests atproto

      - name: Run bluesky_post_joke
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python3 bluesky_post_joke.py

      - name: Update posted_jokes.txt
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Use the GitHub Bot user for Git and GitHub IAM.
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Update posted_jokes.txt to prevent frequent duplications
          git add posted_jokes.txt
          
          # Commit and push
          git commit -m "Update posted_jokes.txt; GH run: ${GITHUB_RUN_NUMBER}"
          git push