name: bluesky_post_joke

on:
  # schedule:
  #   - cron:  '0 0,8,16 * * *'
  workflow_dispatch:

jobs:
  bluesky_post_joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests atproto

      - name: Run bluesky_post_joke
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python3 bluesky_post_joke.py
