name: bluesky-follow-back

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every 2 hours
  workflow_dispatch:  

jobs:
  auto-follow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install atproto colorama python-dotenv

      # Run the auto-follow script
      - name: Run bluesky-follow-back
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python3 bluesky-follow-back.py
