name: bluesky_follow_fellows

on:
  schedule:
    - cron: "0 0 * * 5"  # Runs every Friday at 00:00 UTC
  workflow_dispatch:

jobs:
  bluesky_follow_fellows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run bluesky_follow_fellows
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          BLUESKY_USERNAME: ${{ vars.BLUESKY_USERNAME }}
        run: python bluesky_follow_fellows.py
