name: Keepalive Workflow
on:
  schedule:
    - cron: "15 1 * * *"
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "bluesky_follow_back.yml,bluesky_post_joke.yml,bluesky_unfollow.yml"