name: post-joke

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Don't run on the hour as these can get delayed.
    - cron:  '15 7,19 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post-joke:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests atproto

      - name: Run Joke Bot
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python3 post-joke.py        