name: workflows_disabled

on:
  workflow_dispatch:

permissions: {}

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo 'All workflows are disabled in this branch.'
